# Numpy : Numerical python

In [2]:
import numpy as np

In [2]:
#Deifine an array with integer elements
integerarray= np.array([1,2,3,4],float)

In [3]:
integerarray

array([1., 2., 3., 4.])

In [4]:
integerarray= np.array([1,2,3,4])
integerarray

array([1, 2, 3, 4])

In [5]:
integerarray[0]

1

In [6]:
integerarray[1]

2

In [7]:
#slicing
integerarray[:2]

array([1, 2])

In [9]:
integerarray2 = np.array([5,6])
integerarray2

array([5, 6])

In [10]:
np.concatenate((integerarray,integerarray2))

array([1, 2, 3, 4, 5, 6])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [3]:
#creating array with range function
rangearray =  np.array(range(10),int)
rangearray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
#multidimentional array with string
multi = np.array([['av','bf','ce'],['xr','yx','cp']],str)
multi

array([['av', 'bf', 'ce'],
       ['xr', 'yx', 'cp']], dtype='<U2')

In [27]:
#multidimentional array with number 
muti=np.array([[1,2,3],[4,5,6]],float)
muti

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
multi.shape

(2, 3)

In [22]:
rangearray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
rangearray.shape

(10,)

In [20]:
rangearray = rangearray.reshape(5,2)
rangearray

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
rangearray = rangearray.flatten()
rangearray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# linspace is a tool in Python for creating numeric sequences
# linspace(start,stop,no. of divisons)
data = np.linspace(0,20,5)
data

array([ 0.,  5., 10., 15., 20.])

In [30]:
data = np.linspace(0,20,21)
data

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

# Operations on array

In [32]:
arr1 = np.array([[1,2],[3,4]],int)
arr2 = np.array([[10,20],[30,40]],int)
print(arr1, '\n')
print(arr2, '\n')
np.concatenate((arr1,arr2))

[[1 2]
 [3 4]] 

[[10 20]
 [30 40]] 



array([[ 1,  2],
       [ 3,  4],
       [10, 20],
       [30, 40]])

In [33]:
print("Array  1 \n {} ".format(arr1))

Array  1 
 [[1 2]
 [3 4]] 


In [34]:
a = 12
print("The value is  \n {} ".format(a))

The value is  
 12 


In [38]:
print("New array value is \n {} ".format(arr1+arr2))

New array value is 
 [[11 22]
 [33 44]] 


In [39]:
print("New \n array value is {} ".format(arr1+arr2))

New 
 array value is [[11 22]
 [33 44]] 


In [37]:
np.sqrt(arr1)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [40]:
np.log(arr2)

array([[2.30258509, 2.99573227],
       [3.40119738, 3.68887945]])

In [41]:
print("New array value is \n {} ".format(np.sqrt(arr1)))

New array value is 
 [[1.         1.41421356]
 [1.73205081 2.        ]] 


In [43]:
print("New array value is \n {} ".format(np.log(arr2)))

New array value is 
 [[2.30258509 2.99573227]
 [3.40119738 3.68887945]] 


In [44]:
print("New array value is \n {} ".format(np.sum(arr2)))

New array value is 
 100 


In [45]:
print("New array value is \n {} ".format(np.mean(arr2)))

New array value is 
 25.0 


In [47]:
print("New array value is \n {} ".format(np.std(arr2)))

New array value is 
 11.180339887498949 


In [48]:
print("New array value is \n {} ".format(np.min(arr2)))

New array value is 
 10 


In [49]:
print("New array value is \n {} ".format(np.max(arr2)))

New array value is 
 40 


In [50]:
samplearray = np.array([[5,2,3],[1,4,5],[1,1,1]],int)
samplearray

array([[5, 2, 3],
       [1, 4, 5],
       [1, 1, 1]])

In [51]:
# unique() gives unique values of the array
np.unique(samplearray)

array([1, 2, 3, 4, 5])

In [52]:
# diagonal() gives diagonal eleents of the array
np.diagonal(samplearray)

array([5, 4, 1])

In [53]:
# sort() : sort values of the rows elements 
np.sort(samplearray)

array([[2, 3, 5],
       [1, 4, 5],
       [1, 1, 1]])

In [54]:
# np.random.rand generates random  nubers between 0 ans 1
np.random.rand(5)

array([0.08163942, 0.55629616, 0.30639427, 0.16635888, 0.28508908])

In [55]:
np.random.rand(5,4)

array([[0.730024  , 0.81583669, 0.21707399, 0.7289837 ],
       [0.2856476 , 0.64386523, 0.13522673, 0.20609526],
       [0.54544117, 0.75924528, 0.07525945, 0.09181275],
       [0.03146803, 0.81003871, 0.1861806 , 0.16207089],
       [0.08539598, 0.83702621, 0.69504085, 0.25443697]])

In [57]:
# np.floor return integer part of the values
randomarray = np.floor(np.random.rand(10)*10)
randomarray

array([0., 9., 0., 7., 2., 9., 4., 9., 7., 4.])

In [58]:
# Further simplification 
np.random.randint(0,10,5)

array([5, 7, 9, 6, 2])

In [59]:
np.random.randint(0,10,(2,5))

array([[5, 1, 7, 4, 4],
       [5, 3, 3, 4, 0]])

In [60]:
import time

In [65]:
size = 1000000

l1 = range(size)
l2 = range(size)

arr1 = np.arange(size)
arr2 = np.arange(size)

# calculating time for python list
start = time.time()

result1 = [(x+y) for x,y in zip(l1,l2)]
print('Time elapsed : ' , (time.time() - start))

# calculating time for numpy array
start = time.time()

result2 = (arr1 + arr2)
print('Time elapsed : ' , (time.time() - start))



Time elapsed :  0.284085750579834
Time elapsed :  0.002048015594482422


In [63]:
l1[0],l1[1],l1[2],l1[3],l1[4]

(0, 1, 2, 3, 4)

In [64]:
l2[0],l2[1],l2[2],l2[3],l2[4]

(0, 1, 2, 3, 4)

In [66]:
result1[0],result1[1],result1[2],result1[3],result1[4]

(0, 2, 4, 6, 8)

In [67]:
l1 = ['a','b','c']
l2 = ['x','y','z']

In [68]:
zip(l1,l2)

In [69]:
for x,y in zip(l1,l2):
    print(x,y)

a x
b y
c z


# Dictionary : key value pair

In [4]:
car = {}

In [5]:
type(car)

dict

In [11]:
car = {'Brand':'Ford','model':'Linea','Year':1954}

In [12]:
car.keys()

dict_keys(['Brand', 'model', 'Year'])

In [13]:
car.values()

dict_values(['Ford', 'Linea', 1954])

In [14]:
car.items()

dict_items([('Brand', 'Ford'), ('model', 'Linea'), ('Year', 1954)])

In [15]:
car['Brand']

'Ford'

In [16]:
car['milegae'] = '20k/l'

In [17]:
car

{'Brand': 'Ford', 'model': 'Linea', 'Year': 1954, 'milegae': '20k/l'}

In [18]:
len(car)

4

In [19]:
d = {'d1':'Pradeep','d2':['Kunal','Sree','Anika']}

In [20]:
len(d)

2

In [22]:
d['d1']

'Pradeep'

In [23]:
d['d2']

['Kunal', 'Sree', 'Anika']

In [24]:
Team = {}

Team['Batsman'] = 'Virat'
Team['Bowler'] = 'Shami'
Team['Keeper'] = 'ms'

In [25]:
Team

{'Batsman': 'Virat', 'Bowler': 'Shami', 'Keeper': 'ms'}

In [26]:
Team.get('Batsman')

'Virat'

In [27]:
Team['Batsman']

'Virat'

In [28]:
# Iterating a dictionary
d1 = {'x':100, 'y':200,'z':300}

In [29]:
for i in d1:
    print(i)

x
y
z


In [30]:
for i in d1:
    print(i,'--->',d1[i])

x ---> 100
y ---> 200
z ---> 300


In [31]:
for i in d1.keys():
    print(i)

x
y
z


In [32]:
for i in d1.values():
    print(i)

100
200
300


In [33]:
for i in d1.items():
    print(i)

('x', 100)
('y', 200)
('z', 300)


In [34]:
for i,j in d1.items():
    print(i,'--->',j)

x ---> 100
y ---> 200
z ---> 300


In [1]:
d1 = {'a':100,
     'b':200}

d2 = {'x':300,
     'y':400}

In [2]:
d1.update(d2)

In [3]:
d1

{'a': 100, 'b': 200, 'x': 300, 'y': 400}

In [4]:
d = d1.copy()

In [5]:
d

{'a': 100, 'b': 200, 'x': 300, 'y': 400}

In [6]:
color_dict = {'red':'#FF0000',
             'green':'#000020',
             'yellow':'#000030',
             'blue':'#000040'}

In [7]:
sorted(color_dict)

['blue', 'green', 'red', 'yellow']

In [9]:
for i in sorted(color_dict):
    print('Keys : ',i,'\t','Values : ',color_dict[i])

Keys :  blue 	 Values :  #000040
Keys :  green 	 Values :  #000020
Keys :  red 	 Values :  #FF0000
Keys :  yellow 	 Values :  #000030


# Functions

In [11]:
def simple():
    
    print('simple function')
    print('First function')
    
print('Not a part of function')

Not a part of function


In [12]:
simple()

simple function
First function


In [13]:
#Function
def plus_ten(a):
    return a+10
# This time we are returing value like last

In [14]:
plus_ten(22)

32

In [15]:
x = plus_ten(22)

In [16]:
x

32

In [1]:
def minus_ten(a):
    result = a - 10

In [2]:
minus_ten(33)
# no value is seen because there is no retun

In [19]:
def wage(w_hour):
    print('Enterd wage function')
    return w_hour*25

def wage_bonus(w_hour):
    print('Ented wage bonus function')
    return wage(w_hour)+50

In [20]:
wage(20)

Enterd wage function


500

In [21]:
wage_bonus(20)

Ented wage bonus function
Enterd wage function


550

In [24]:
# we can also pass a data sturcture as parameter 

def y_function(food):
    for x in food:
        print(x)
    print('For loop ended')

fruits = ['apple','orange','kiwi']

In [25]:
y_function(fruits)

apple
orange
kiwi
For loop ended


In [3]:
# Python exercise to remove duplicates from dictionary
student_data = {'id1':
               {'Nae': ['Sara'],
               'class' : ['V'],
                'Subject_integreation': ['English','Math','Science']
               },
               'id2':
               {'Nae': ['David'],
               'class' : ['V'],
                'Subject_integreation': ['English','Math','Science']
               },
                'id3':
               {'Nae': ['Sara'],
               'class' : ['V'],
                'Subject_integreation': ['English','Math','Science']
               },
                'id4':
               {'Nae': ['Surya'],
               'class' : ['V'],
                'Subject_integreation': ['English','ath','Science']
               },
               }

In [4]:
len(student_data)

4

In [5]:
result = {}

for key,value in student_data.items():
    
    if value not in result.values():
        
        result[key] = value
        
print(result)

{'id1': {'Nae': ['Sara'], 'class': ['V'], 'Subject_integreation': ['English', 'Math', 'Science']}, 'id2': {'Nae': ['David'], 'class': ['V'], 'Subject_integreation': ['English', 'Math', 'Science']}, 'id4': {'Nae': ['Surya'], 'class': ['V'], 'Subject_integreation': ['English', 'ath', 'Science']}}
